### PR TITLE
Improve layers so that they can be passed easily by LayerInfo and not only by index

### PR DESCRIPTION
**Pull request by sebastian-goeldi**
TODO:
- [x] make `Layers` better
- [x] allow dynamic creation and registering of `Layers`

### CODE REVIEW

**Comment by sebastian-goeldi** [comment]
The new structure will allow this:

```python
import kfactory as kf


class Constants(kf.kcell.Constants):
    WG_WIDTH: int = 2000


class Layers(kf.kcell.LayerInfos):
    WG: kf.kdb.LayerInfo = kf.kdb.LayerInfo(1, 0, "WG")
    WGEX: kf.kdb.LayerInfo = kf.kdb.LayerInfo(1, 1, "WG")


kcl = kf.KCLayout[Layers, Constants]("TEST", layer_infos=Layers, constants=Constants)
c = kcl.kcell()

kcl.constants.WG_WIDTH

c.kcl.layer_infos.WG
c.kcl.layer_infos.CLAD

c.kcl.constants.WG
c.kcl.constatns.WGEX
```

Autocompletion currently only works for `kcl.constants` and `kcl.layer_infos`.
image

Mypy is able to detect missing/wrong fields though
image


Is the increased complexity worth it though? These changes will necessitate that we do

`kcl.kcell()` in the future instead of `kf.KCell(...)` (because otherwise we would need to do  `kf.KCell[MyLayerInfosClass, MyConstantsClass](kcl=kcl)`

@gdspaul @joamatab @tvt173

**Comment by gdspaul** [comment]
do you mean that users who are happy to use the default `kcl` are still going to have to type `kf.kcl.kcell` to make a cell?

**Comment by sebastian-goeldi** [comment]
not really, this works perfectly fine (just mypy complaining in my case):

```python
import kfactory as kf

c = kf.KCell()

c.shapes(c.kcl.layer(1, 0)).insert(kf.kdb.Box(500))
c.show()
```

**Comment by gdspaul** [comment]
does the layerinfo init really need a layer name put in? it's been hard to sneak nice things past mypy here, but maybe there's a way to internally set layerinfo.name to match the layer attribute names without annoying mypy. pseudopython—
```
class Layers(baseclass):
 WG = layerinfo(1,0) # wire it up internally to become layerinfo(1,0,'WG')
```

**Comment by sebastian-goeldi** [comment]
> does the layerinfo init really need a layer name put in? it's been hard to sneak nice things past mypy here, but maybe there's a way to internally set layerinfo.name to match the layer attribute names without annoying mypy. pseudopython—
> 
> ```
> class Layers(baseclass):
>  WG = layerinfo(1,0) # wire it up internally to become layerinfo(1,0,'WG')
> ```

It does not in fact, but what it needs is the type annotation due to it being a pydantic model, unfortunately.

so it's happy with

```python
class Layers(kf.kcell.LayerInfos):
    WG: kf.kdb.LayerInfo = kf.kdb.LayerInfo(1, 0)


and it will make it to `WG: kf.kdb.LayerInfo = kf.kdb.LayerInfo(1, 0, "WG")` but `: kf.kdb.LayerInfo` is necessary

**Comment by sebastian-goeldi** [comment]
dataclasses are also not great if you want stuff like `asdict` to work properly, so I don't have a great solution for that.

**Comment by gdspaul** [comment]
my comment was confusing, my bad. the layers concept isn't a good fit for dataclasses either. but maybe there's *something* that could be implemented—let's call it `UserFacingLayersBaseClass`, so user code could read
```
class Layers(UserFacingLayersBaseClass):
 WG = kf.kdb.LayerInfo(1,0)
```
which does not need to be annotated, and then there's some function in the KCLayout infrastructure that does this job:
```
# user_defined_layer_class = Layers
pdk_layers: ActualLayersPydanticModel = make_pydantic_thingy_from_user_class(user_defined_layer_class)
# validation is done
pdk.layers = pdk_layers
pdk.layers.model_dump() # but Layers.model_dump() is not defined
```

**Comment by sebastian-goeldi** [comment]
I don't think that would work. I mean you are free to do any of this. You just can't pass it to the KCLayout creation.

But you can always do this if you do not want autocomplete

```python
kcl.layer_infos = kf.kcell.LayerInfos(WG=kf.kdb.LayerInfo(1,0))
```

**Pull request merged**
