### PR TITLE
Add info to ports and allow named Instances

### PR DESCRIPTION
**Pull request by sebastian-goeldi**
Fixes #74  #75 

@joamatab

### CODE REVIEW

**Comment by sebastian-goeldi** [comment]
Example:

```
import kfactory as kf


c = kf.KCell()


wg = kf.pcells.waveguide.waveguide(length=10, width=1, layer=c.klib.layer(1, 0))

wg1 = c << wg
wg1.name = "wg1"


wg2 = c << wg

wg2.align("o1", wg1, "o2")

c.show()
```
image

**Comment by joamatab** [comment]
This is great Sebastian,

would this work with OASIS?

**Comment by sebastian-goeldi** [comment]
OASIS takes strings or int keys, so it should work with OASIS yes. In OASIS it would even be possible to do `name: "wg1`

**Comment by joamatab** [comment]
amazing! :)

**Pull request merged**
