### PR TITLE
Gdsfactory cells

### PR DESCRIPTION
**Pull request by joamatab**
- rename autocell to pcell (makes more sense)
- add compass pcell

### CODE REVIEW

**Comment by sgoeldi-psiq** [comment]
any reason for not using a `klayout.db.Box` instead of a compass? In KLayout there is really no reason to use a compass, imo.

**Comment by sebastian-goeldi** [comment]
Why not use `kdb.Box` or `kdb.DBox` instead of a compass? It is much leaner and gives you everything you want from a compass.

**Comment by sebastian-goeldi** [comment]
w.r.t. to the renaming to pcell. I think this would be super confusing with this [guy](https://www.klayout.de/doc-qt5/code/class_PCellDeclarationHelper.html). It is in fact not one of those, nor should it ever be.

**Comment by sebastian-goeldi** [comment]
And why add `if __name__ ...` blocks to cells? if you want something like that, write a test ;)

**Comment by joamatab** [comment]
`cell` sounds also good to me,

**Pull request closed without merging**
