### PR TITLE
add info to ports

### PR DESCRIPTION
**Pull request by joamatab**
add info to ports for keeping gdsfactory compatibility

@sebastian-goeldi

### CODE REVIEW

**Comment by sebastian-goeldi** [comment]
What kind of info do you need to dump into ports? this will break when we get this https://github.com/KLayout/klayout/issues/1341

**Comment by sebastian-goeldi** [comment]
If you need gdsfactory compatibility you should be able to just inherit from this class and add it, can't you?

**Comment by sebastian-goeldi** [comment]
Also I am currently working on making the CplxKCell obsolete

**Comment by joamatab** [comment]
we usually use the `info` dict for simulation metadata

**Pull request closed without merging**
