### PR TITLE
pdk migration pydantic-2

### PR DESCRIPTION
**Pull request by sebastian-goeldi**

### CODE REVIEW

**Comment by sebastian-goeldi** [comment]
TODO:

Reimplement the technology parts

**Comment by joamatab** [comment]
@thomasdorch

**Comment by sebastian-goeldi** [comment]
Local test (so far):

```python
import kfactory as kf

kf.technology.layer_map.yaml_to_lyp("test.yml", "test.lyp")
```

<details>

<summary>test.yml</summary>

```yaml
layers:
- name: Waveguide
  layer: [1, 0]
  dither_pattern: dotted
  width: 1
  color: "#ff9d9d"
- name: Waveguide
  layer: [1, 0]
  dither_pattern: dotted
  width: 1
  color: "red"
- name: group1
  members:
    - name: NPP
      color: "cyan"
      layer: [5,0]
    - name: subgroup1
      members:
        - name: subsub1
          layer: [15,0]
```

</details>

produces:

<details>

<summary>test.lyp</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-properties>
 <properties>
  <expanded>false</expanded>
  <frame-color/>
  <fill-color/>
  <frame-brightness>0</frame-brightness>
  <fill-brightness>0</fill-brightness>
  <dither-pattern>I2</dither-pattern>
  <line-style/>
  <valid>true</valid>
  <visible>true</visible>
  <transparent>false</transparent>
  <width>1</width>
  <marked>false</marked>
  <xfill>false</xfill>
  <animation>0</animation>
  <name>Waveguide - 1/0</name>
  <source>1/0@1</source>
 </properties>
 <properties>
  <expanded>false</expanded>
  <frame-color/>
  <fill-color/>
  <frame-brightness>0</frame-brightness>
  <fill-brightness>0</fill-brightness>
  <dither-pattern>I2</dither-pattern>
  <line-style/>
  <valid>true</valid>
  <visible>true</visible>
  <transparent>false</transparent>
  <width>1</width>
  <marked>false</marked>
  <xfill>false</xfill>
  <animation>0</animation>
  <name>Waveguide - 1/0</name>
  <source>1/0@1</source>
 </properties>
 <properties>
  <expanded>false</expanded>
  <frame-color/>
  <fill-color/>
  <frame-brightness>0</frame-brightness>
  <fill-brightness>0</fill-brightness>
  <dither-pattern/>
  <line-style/>
  <valid>true</valid>
  <visible>true</visible>
  <transparent>false</transparent>
  <width/>
  <marked>false</marked>
  <xfill>false</xfill>
  <animation>0</animation>
  <name>group1</name>
  <source>*/*@*</source>
  <group-members>
   <expanded>false</expanded>
   <frame-color/>
   <fill-color/>
   <frame-brightness>0</frame-brightness>
   <fill-brightness>0</fill-brightness>
   <dither-pattern>I1</dither-pattern>
   <line-style/>
   <valid>true</valid>
   <visible>true</visible>
   <transparent>false</transparent>
   <width>1</width>
   <marked>false</marked>
   <xfill>false</xfill>
   <animation>0</animation>
   <name>NPP - 5/0</name>
   <source>5/0@1</source>
  </group-members>
  <group-members>
   <expanded>false</expanded>
   <frame-color/>
   <fill-color/>
   <frame-brightness>0</frame-brightness>
   <fill-brightness>0</fill-brightness>
   <dither-pattern/>
   <line-style/>
   <valid>true</valid>
   <visible>true</visible>
   <transparent>false</transparent>
   <width/>
   <marked>false</marked>
   <xfill>false</xfill>
   <animation>0</animation>
   <name>subgroup1</name>
   <source>*/*@*</source>
   <group-members>
    <expanded>false</expanded>
    <frame-color/>
    <fill-color/>
    <frame-brightness>0</frame-brightness>
    <fill-brightness>0</fill-brightness>
    <dither-pattern>I1</dither-pattern>
    <line-style/>
    <valid>true</valid>
    <visible>true</visible>
    <transparent>false</transparent>
    <width>1</width>
    <marked>false</marked>
    <xfill>false</xfill>
    <animation>0</animation>
    <name>subsub1 - 15/0</name>
    <source>15/0@1</source>
   </group-members>
  </group-members>
 </properties>
 <name/>
</layer-properties>
```

</details>

@SkandanC @joamatab does this seem reasonable? ofc we can add the other way as soon as we are happy with yaml -> lyp

**Comment by sebastian-goeldi** [comment]
Added lyp -> yaml

**Pull request merged**
